import { Key } from './Key';

export interface Account {
  active: Key;
  balance: string;
  can_vote: boolean;
  comment_count: number;
  created: string;
  curation_rewards: number;
  delegated_vesting_shares: string;
  guest_bloggers: any[];
  id: number;
  json_metadata: string;
  last_account_recovery: string;
  last_account_update: string;
  last_owner_update: string;
  last_post: string;
  last_root_post: string;
  last_vote_time: string;
  lifetime_vote_count: number;
  market_history: any[];
  memo_key: string;
  mined: boolean;
  name: string;
  next_vesting_withdrawal: string;
  other_history: any[];
  owner: Key;
  post_count: number;
  post_history: any[];
  posting: Key;
  posting_rewards: number;
  proxied_vsf_votes: number[];
  proxy: string;
  received_vesting_shares: string;
  recovery_account: string;
  reputation: string;
  reset_account: string;
  reward_sbd_balance: string;
  reward_steem_balance: string;
  reward_vesting_balance: string;
  reward_vesting_steem: string;
  savings_balance: string;
  savings_sbd_balance: string;
  savings_sbd_last_interest_payment: string;
  savings_sbd_seconds: string;
  savings_sbd_seconds_last_update: string;
  savings_withdraw_requests: number;
  sbd_balance: string;
  sbd_last_interest_payment: string;
  sbd_seconds: string;
  sbd_seconds_last_update: string;
  tags_usage: any[];
  to_withdraw: number;
  transfer_history: any[];
  vesting_balance: string;
  vesting_shares: string;
  vesting_withdraw_rate: string;
  vote_history: any[];
  voting_power: number;
  withdraw_routes: number;
  withdrawn: number;
  witness_votes: any[];
  witnesses_voted_for: number;
}

export interface Follower {
  follower: string;
  following: string;
  what: string[];
}
