version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 743e68e5778119121775c142489962cb416aa393395320d3704358ab15d1c740
      CODACY_PROJECT_TOKEN: 1c1c8a6d0c9045be970fc9de931ad029
    working_directory: ~/typesteem
    docker:
      - image: circleci/node:11.12.0
    steps:
      - checkout
      - run: mkdir reports
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run:
          name: install-reporters
          command: npm install mocha-junit-reporter codacy-coverage # just for CircleCI

      - run:
          name: install-npm
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: compile-dist
          command: npm run compile

      # Run mocha
      - run:
          name: npm test
          command: ./node_modules/.bin/nyc ./node_modules/.bin/mocha --reporter mocha-junit-reporter --reporter-options mochaFile=reports/mocha/test-results.xml
          when: always

      # Run eslint
      - run:
          name: tslint
          command: |
            npm run lint

      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
          when: always

      - run:
          name: code-coverage
          command: |
            mkdir coverage
            # nyc report requires that nyc has already been run,
            # which creates the .nyc_output folder containing necessary data
            ./node_modules/.bin/nyc report --reporter=text-lcov > coverage/lcov.info
            ./cc-test-reporter after-build -t lcov
          when: always

      - run:
          name: codacy-report
          command: cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage

      # Upload results

      - store_test_results:
          path: reports

      - store_artifacts:
          path: ./reports/mocha/test-results.xml

      - store_artifacts:
          path: ./reports/tslint/tslint.xml

      - store_artifacts: # upload test coverage as artifact
          path: ./coverage/lcov.info
          prefix: tests
